### ISSUE TITLE
django-papertrail requires "target" objects to be registered with Django's ModelAdmin

### ISSUE THREAD

**Issue by theGOTOguy** [FundersClub/django-papertrail#7]
Undocumented in django-papertrail is that all objects in "target" must be registered with Django's ModelAdmin, or otherwise loading the log message's page in the Django admin panel will fail ungracefully.  I see a couple of ways forward here:

1)  This could simply be a documentation fix.
2)  We could check targets at the time they're added to django-papertrail to see whether these targets are part of ModelAdmin, and raise an error if they are not.  This has the weakness that if at some point in the future a model was removed from the ModelAdmin, this error would occur and be difficult to understand or debug.
3)  We could check in the admin_reverse_for_model function whether said model is in ModelAdmin (or catch the error here when the reverse isn't found), and if it's not then simply print a warning in place of the ModelAdmin link that a developer needs to add said model to ModelAdmin in order for it to be visible in django-papertrail.

I love django-papertrail, and if you advise on your favorite approach to resolving this issue, I'd be happy to submit a PR.

**Comment by eranrund** [comment]
Hello!

Good catch. I think the solution I'd like the most is a variation of number 3. I would simply catch the error and just not render a link in case the model isn't registered. It's a small change so I can do it myself and release a new version in the next day or so.

Glad to hear you are enjoying this package!

**Comment by eranrund** [comment]
Fixed in 143ecb8b31e06bc667ebc8b10acca8e30bf3c29a. Version 1.1.6 released which has this fix.

**Comment by theGOTOguy** [comment]
Thank you!
